### ISSUE TITLE
US5 show all infos of a card

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project-typescript#4]
## Value Proposition

**As a** user 
**I want to** also see the all other infos about the matched players in the cards  
**so that** I can choose wisely my teammates
​

## Description

![image](https://user-images.githubusercontent.com/116001970/208344919-9db4be6c-42af-474f-bbca-036ca30fce49.png)

## Acceptance Criteria

- [ ] all the Infos about a player are shown in the card
- [ ] the layout is mobile friendly
- [ ] scroll direction of the matched cards is horizontal

## Tasks

- [ ] add a css overflow-x scroll to the card wrapper

      ​

**Comment by AntjeWalter** [comment]
Hi Walter, do I understand it correctly, that in this US you can see all the players that match the chosen characteristics and you can scroll to see them all but not contact or add them in any way? Because if so, the Value Proposition should be changed to something like "to be able to have an overview of all possible matches" or similar i think :)

**Comment by WalterRestifo** [comment]
You are totally right Antje, I fix it asap
