### ISSUE TITLE
US6 matching part 2

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project-typescript#5]
## Value Proposition

**As a** user 
**I want to** only want to see cards of players that are looking for players like me 
**so that** I don´t contact someone that don´t want to play with me
​

## Description

![image](https://user-images.githubusercontent.com/116001970/208346818-b6b13885-7b13-4797-937c-0f34e02134e8.png)

## Acceptance Criteria

- [ ] only people that looks for the criteria of my own card are displayed
- [ ] the chosen criteria of my search are saved in a DB within the data of my own card

## Tasks

- [ ] add dummy filter criteria for the dummy data of the other players
- [ ] save all in a mongodb 
      ​

**Comment by AntjeWalter** [comment]
I'm not sure about how you want to make this match work and how to test it. Maybe you could be a bit clearer in your tasks.

**Comment by WalterRestifo** [comment]
Hi, I hope it is better now. I too don´t exactly know how to do it, that is why I cannot write much in the tasks. My dev team is a skilled one, I trust in their capabilities to find a solution 🤣
