### ISSUE TITLE
US9 make it pretty

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project-typescript#7]
## Value Proposition

**As a** user 
**I want to** see a pretty app
**in order to** be happy with the look of the app
​

## Description
I don't have an exact plan of how it should look like

## Acceptance Criteria

- [ ] it looks good
- [ ] the layout is mobile friendly

## Tasks

- [ ] find good color combinations
- [ ] do your best
