### ISSUE TITLE
US8 Navbar

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/capstone-project-typescript#8]
## Value Proposition

**As a** user 
**I want to** have a navbar
**in order to** switch between the pages of the app
​

## Description

![image](https://user-images.githubusercontent.com/116001970/210589623-2ebcf965-f7a3-4e48-ad5f-45f2a3671623.png)

## Acceptance Criteria

- [ ] the navbar can be used to switch between the pages of the app
- [ ] the layout of the navbar is mobile friendly
- [ ] the navbar is by scrolling always at the bottom of the screen of the smartphone

## Tasks

- [ ] code a navbar component
- [ ] make it sticky

**Comment by flipkoehler** [comment]
Hey Walter, 
this looks like a nice feature. Also a nice user story :)
